### ISSUE TITLE
Implementar componente de comando de emenda de texto livre

### ISSUE THREAD

**Issue by fragomeni** [lexml/lexml-eta#627]
Isolar o editor da justificativa em um componente de edição de texto rico que será utilizado tanto na justificativa quanto para o comando de texto livre.

**Comment by fragomeni** [comment]
Reprovado no teste:

1 - Na aplicação demo, só está sendo possível criar inicialmente uma emenda de texto livre 

O primeiro teste que fiz foi iniciar o lexml-eta e clicar no ok (com a seleção padrão mesmo) para começar uma emenda normal. Não funcionou.


2 - A indentação da primeira linha dos parágrafos justificados no editor html foi perdida

![Image](https://github.com/lexml/lexml-eta/assets/5323676/cb8a4bff-3619-4c80-b05c-b88c0f030bde)

3 - Fica lançando a exception:

Uncaught TypeError: this.quill.cursorDeTextoEstaSobreLink is not a function
    at HTMLDivElement.<anonymous> (eta-keyboard.ts:42:24)

4 - Ao abrir uma emenda comum, é lançada a exception

lexml-emenda.component.ts:173 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setContent')
    at LexmlEmendaComponent.setEmenda (lexml-emenda.component.ts:173:32)
    at LexmlEmendaComponent.inicializarEdicao (lexml-emenda.component.ts:155:12)
    at fReader.onloadend (demoview.ts:169:30)
